version: '3.7'

services:
  custom-app:
    container_name: custom-app
    image: ypblrb/name:v2
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Group-65
    networks:
      - backend

networks:
  backend:
    driver: bridge
